/* The following code was generated by JFlex 1.5.1 */

package Analizador;
import java_cup.runtime.Symbol;
import java.util.LinkedList;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.1
 * from the specification file <tt>Scanner.txt</tt>
 */
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 46, 46, 47, 46, 46,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    40, 45,  0,  0,  0, 25, 44,  0, 28, 29, 23, 22, 38, 20, 41, 24, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 39,  0, 31, 27, 30,  0, 
     0,  9, 10, 11, 12,  3, 16,  1, 36, 35,  1,  1,  8, 33,  4,  7, 
    37,  1,  6, 18,  5,  1, 15,  1, 42,  1,  1, 13,  0, 14, 26, 32, 
     0,  9, 10, 11, 12,  3, 16,  1, 36, 35,  1,  1,  8, 33,  4,  7, 
    37,  1,  6, 18,  5,  1, 15,  1, 42,  1,  1, 19, 43, 21,  0,  0, 
     0,  0,  0,  0,  0, 47,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\6\2\1\1\2\2\1\1"+
    "\1\2\1\1\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\3\2\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\21\10\2\1\25\1\26"+
    "\1\0\3\2\1\0\1\2\1\0\1\2\2\0\1\27"+
    "\1\0\13\2\1\30\1\2\1\31\1\2\2\32\1\0"+
    "\1\2\3\0\2\2\1\0\6\2\1\33\4\2\1\0"+
    "\1\2\1\0\1\2\4\0\2\2\1\0\1\2\1\34"+
    "\1\2\1\35\6\2\2\36\1\0\1\2\4\0\1\2"+
    "\1\37\2\40\1\41\1\2\1\42\2\2\1\43\1\2"+
    "\1\0\1\2\2\0\5\2\1\0\1\2\2\0\5\2"+
    "\1\0\1\2\1\44\2\45\3\2\1\46\2\47\2\2"+
    "\1\50\1\2\1\0\1\2\1\0\1\2\1\0\1\2"+
    "\1\0\1\2\2\51\2\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[180];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\360\0\u0120\0\u0150"+
    "\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240\0\u0270\0\u02a0\0\u02d0"+
    "\0\60\0\60\0\60\0\60\0\60\0\60\0\60\0\60"+
    "\0\60\0\60\0\60\0\u0300\0\u0330\0\u0360\0\60\0\60"+
    "\0\60\0\60\0\60\0\60\0\u0390\0\u03c0\0\u03f0\0\u0420"+
    "\0\u0450\0\u0480\0\u04b0\0\u04e0\0\u0510\0\140\0\140\0\u0540"+
    "\0\u0570\0\u05a0\0\u05d0\0\u0600\0\u0630\0\u0660\0\u0690\0\u06c0"+
    "\0\u06f0\0\60\0\u0720\0\u0750\0\u0780\0\u07b0\0\u07e0\0\u0810"+
    "\0\u0840\0\u0870\0\u08a0\0\u08d0\0\u0900\0\u0930\0\60\0\u0960"+
    "\0\140\0\u0990\0\60\0\140\0\u09c0\0\u09f0\0\u0a20\0\u0a50"+
    "\0\u0a80\0\u0ab0\0\u0ae0\0\u0b10\0\u0b40\0\u0b70\0\u0ba0\0\u0bd0"+
    "\0\u0c00\0\u0c30\0\140\0\u0c60\0\u0c90\0\u0cc0\0\u0cf0\0\u0d20"+
    "\0\u0d50\0\u0d80\0\u0db0\0\u0de0\0\u0e10\0\u0e40\0\u0e70\0\u0ea0"+
    "\0\u0ed0\0\u0f00\0\u0f30\0\140\0\u0f60\0\140\0\u0f90\0\u0fc0"+
    "\0\u0ff0\0\u1020\0\u1050\0\u1080\0\60\0\140\0\u10b0\0\u10e0"+
    "\0\u1110\0\u1140\0\u1170\0\u11a0\0\u11d0\0\140\0\60\0\140"+
    "\0\140\0\u1200\0\140\0\u1230\0\u1260\0\140\0\u1290\0\u12c0"+
    "\0\u12f0\0\u1320\0\u1350\0\u1380\0\u13b0\0\u13e0\0\u1410\0\u1440"+
    "\0\u1470\0\u14a0\0\u14d0\0\u1500\0\u1530\0\u1560\0\u1590\0\u15c0"+
    "\0\u15f0\0\u1620\0\u1650\0\60\0\60\0\140\0\u1680\0\u16b0"+
    "\0\u16e0\0\140\0\60\0\140\0\u1710\0\u1740\0\140\0\u1770"+
    "\0\u17a0\0\u17d0\0\u1800\0\u1830\0\u1860\0\u1890\0\u18c0\0\u18f0"+
    "\0\60\0\140\0\60\0\140";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[180];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\4\3\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\2\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\2\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\2\1\34\1\2"+
    "\1\3\1\35\1\36\1\37\1\40\1\41\1\2\1\3"+
    "\1\42\1\43\1\44\1\45\62\0\14\3\2\0\2\3"+
    "\1\0\1\3\15\0\2\3\1\0\3\3\4\0\1\3"+
    "\7\0\1\4\56\0\3\3\1\46\10\3\2\0\2\3"+
    "\1\0\1\3\15\0\2\3\1\0\3\3\4\0\1\3"+
    "\6\0\2\3\1\47\11\3\2\0\2\3\1\0\1\3"+
    "\15\0\2\3\1\0\3\3\4\0\1\3\6\0\3\3"+
    "\1\50\3\3\1\51\4\3\2\0\2\3\1\0\1\3"+
    "\15\0\2\3\1\0\3\3\4\0\1\3\6\0\6\3"+
    "\1\52\5\3\2\0\2\3\1\0\1\3\15\0\2\3"+
    "\1\0\3\3\4\0\1\3\6\0\5\3\1\53\1\54"+
    "\1\3\1\55\3\3\2\0\2\3\1\0\1\3\15\0"+
    "\2\3\1\0\3\3\4\0\1\3\6\0\12\3\1\56"+
    "\1\3\2\0\1\57\1\3\1\0\1\3\15\0\2\3"+
    "\1\0\3\3\4\0\1\3\6\0\14\60\2\0\2\60"+
    "\1\0\1\60\16\0\1\60\1\0\3\60\4\0\1\60"+
    "\6\0\2\3\1\61\5\3\1\62\3\3\2\0\2\3"+
    "\1\0\1\3\15\0\2\3\1\0\3\3\4\0\1\3"+
    "\6\0\10\3\1\63\3\3\2\0\2\3\1\0\1\3"+
    "\15\0\2\3\1\64\1\65\2\3\4\0\1\3\10\0"+
    "\1\66\55\0\2\3\1\67\11\3\2\0\2\3\1\0"+
    "\1\3\15\0\2\3\1\0\3\3\4\0\1\3\6\0"+
    "\1\70\1\71\12\70\2\0\2\70\1\0\1\70\1\0"+
    "\1\71\1\72\13\0\1\70\1\0\3\70\4\0\1\70"+
    "\6\0\14\3\2\0\2\3\1\0\1\3\15\0\2\3"+
    "\1\73\1\74\2\3\4\0\1\3\6\0\10\3\1\75"+
    "\3\3\2\0\2\3\1\0\1\3\15\0\2\3\1\0"+
    "\3\3\4\0\1\3\6\0\10\3\1\76\3\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\63\0\1\45\2\0\4\3\1\77\7\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\6\0\4\3\1\100\7\3\2\0\2\3\1\0"+
    "\1\3\15\0\2\3\1\0\3\3\4\0\1\3\6\0"+
    "\2\3\1\101\11\3\2\0\2\3\1\0\1\3\15\0"+
    "\2\3\1\0\3\3\4\0\1\3\6\0\2\3\1\102"+
    "\11\3\2\0\2\3\1\0\1\3\15\0\2\3\1\0"+
    "\3\3\4\0\1\3\6\0\6\3\1\103\5\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\6\0\2\3\1\104\11\3\2\0\2\3\1\0"+
    "\1\3\15\0\2\3\1\0\3\3\4\0\1\3\6\0"+
    "\3\3\1\105\10\3\2\0\2\3\1\0\1\3\15\0"+
    "\2\3\1\0\3\3\4\0\1\3\6\0\13\3\1\106"+
    "\2\0\2\3\1\0\1\3\15\0\2\3\1\0\3\3"+
    "\4\0\1\3\23\0\1\107\42\0\5\3\1\110\6\3"+
    "\2\0\2\3\1\0\1\3\15\0\2\3\1\0\3\3"+
    "\4\0\1\3\6\0\5\3\1\111\6\3\2\0\2\3"+
    "\1\0\1\3\15\0\2\3\1\0\3\3\4\0\1\3"+
    "\6\0\7\3\1\112\4\3\2\0\2\3\1\0\1\3"+
    "\15\0\2\3\1\0\3\3\4\0\1\3\11\0\1\113"+
    "\54\0\3\3\1\114\10\3\2\0\2\3\1\0\1\3"+
    "\15\0\2\3\1\0\3\3\4\0\1\3\52\0\1\115"+
    "\13\0\14\3\2\0\2\3\1\0\1\3\15\0\2\3"+
    "\1\0\2\3\1\116\4\0\1\3\6\0\1\117\1\71"+
    "\12\117\2\0\2\117\1\0\1\117\1\0\1\71\1\72"+
    "\13\0\1\117\1\0\3\117\1\0\1\120\2\0\1\117"+
    "\6\0\14\71\2\0\2\71\1\0\1\71\1\0\1\71"+
    "\1\72\13\0\1\71\1\0\3\71\4\0\1\71\10\0"+
    "\1\121\55\0\2\3\1\122\11\3\2\0\2\3\1\0"+
    "\1\3\15\0\2\3\1\0\3\3\4\0\1\3\6\0"+
    "\12\3\1\123\1\3\2\0\2\3\1\124\1\125\15\0"+
    "\2\3\1\0\3\3\4\0\1\3\6\0\5\3\1\126"+
    "\6\3\2\0\2\3\1\0\1\3\15\0\2\3\1\0"+
    "\3\3\4\0\1\3\6\0\2\3\1\127\11\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\6\0\5\3\1\130\6\3\2\0\2\3\1\0"+
    "\1\3\15\0\2\3\1\0\3\3\4\0\1\3\6\0"+
    "\14\3\2\0\2\3\1\0\1\3\15\0\2\3\1\0"+
    "\3\3\4\0\1\131\6\0\4\3\1\132\7\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\6\0\7\3\1\133\4\3\2\0\2\3\1\0"+
    "\1\3\15\0\2\3\1\0\3\3\4\0\1\3\6\0"+
    "\10\3\1\134\3\3\2\0\2\3\1\0\1\3\15\0"+
    "\2\3\1\0\3\3\4\0\1\3\6\0\12\3\1\135"+
    "\1\3\2\0\2\3\1\0\1\3\15\0\2\3\1\0"+
    "\3\3\4\0\1\3\6\0\2\3\1\136\11\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\6\0\13\3\1\137\2\0\2\3\1\0\1\3"+
    "\15\0\2\3\1\0\3\3\4\0\1\3\6\0\14\3"+
    "\2\0\2\3\1\140\1\141\15\0\2\3\1\0\3\3"+
    "\4\0\1\3\16\0\1\142\47\0\10\3\1\143\3\3"+
    "\2\0\2\3\1\0\1\3\15\0\2\3\1\0\3\3"+
    "\4\0\1\3\6\0\14\117\2\0\2\117\1\0\1\117"+
    "\1\0\1\71\1\72\12\0\1\144\1\117\1\0\3\117"+
    "\3\0\1\145\1\117\35\0\1\146\33\0\1\147\54\0"+
    "\3\3\1\150\10\3\2\0\2\3\1\0\1\3\15\0"+
    "\2\3\1\0\3\3\4\0\1\3\6\0\2\3\1\151"+
    "\11\3\2\0\2\3\1\0\1\3\15\0\2\3\1\0"+
    "\3\3\4\0\1\3\12\0\1\152\53\0\4\3\1\153"+
    "\7\3\2\0\2\3\1\0\1\3\15\0\2\3\1\0"+
    "\3\3\4\0\1\3\6\0\10\3\1\154\3\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\6\0\5\3\1\155\6\3\2\0\2\3\1\0"+
    "\1\3\15\0\2\3\1\0\3\3\4\0\1\3\6\0"+
    "\10\3\1\156\3\3\2\0\2\3\1\0\1\3\15\0"+
    "\2\3\1\0\3\3\4\0\1\3\6\0\10\3\1\157"+
    "\3\3\2\0\2\3\1\0\1\3\15\0\2\3\1\0"+
    "\3\3\4\0\1\3\6\0\5\3\1\160\6\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\6\0\5\3\1\161\6\3\2\0\2\3\1\0"+
    "\1\3\15\0\2\3\1\0\3\3\4\0\1\3\6\0"+
    "\10\3\1\162\3\3\2\0\2\3\1\0\1\3\15\0"+
    "\2\3\1\0\3\3\4\0\1\3\6\0\3\3\1\163"+
    "\10\3\2\0\2\3\1\0\1\3\15\0\2\3\1\0"+
    "\3\3\4\0\1\3\6\0\10\3\1\164\3\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\14\0\1\165\51\0\6\3\1\166\5\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\13\0\1\167\52\0\5\3\1\170\6\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\6\0\14\144\2\0\2\144\1\0\1\144\15\0"+
    "\2\144\1\0\3\144\3\0\1\145\1\144\12\0\1\171"+
    "\53\0\1\172\1\173\12\172\2\0\2\172\1\0\1\172"+
    "\15\0\1\173\1\172\1\0\3\172\2\0\1\173\1\0"+
    "\1\172\12\0\1\174\53\0\4\3\1\175\7\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\6\0\5\3\1\176\6\3\2\0\2\3\1\0"+
    "\1\3\15\0\2\3\1\0\3\3\4\0\1\3\16\0"+
    "\1\177\47\0\10\3\1\200\3\3\2\0\2\3\1\0"+
    "\1\3\15\0\2\3\1\0\3\3\4\0\1\3\6\0"+
    "\6\3\1\201\5\3\2\0\2\3\1\0\1\3\15\0"+
    "\2\3\1\0\3\3\4\0\1\3\6\0\5\3\1\202"+
    "\6\3\2\0\2\3\1\0\1\3\15\0\2\3\1\0"+
    "\3\3\4\0\1\3\6\0\10\3\1\203\3\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\6\0\14\3\2\0\2\3\1\0\1\3\15\0"+
    "\1\204\1\3\1\0\3\3\4\0\1\3\6\0\4\3"+
    "\1\205\7\3\2\0\2\3\1\0\1\3\15\0\2\3"+
    "\1\0\3\3\4\0\1\3\6\0\10\3\1\206\3\3"+
    "\2\0\2\3\1\0\1\3\15\0\2\3\1\0\3\3"+
    "\4\0\1\3\6\0\13\3\1\207\2\0\2\3\1\0"+
    "\1\3\15\0\2\3\1\0\3\3\4\0\1\3\16\0"+
    "\1\210\47\0\10\3\1\211\3\3\2\0\2\3\1\0"+
    "\1\3\15\0\2\3\1\0\3\3\4\0\1\3\57\0"+
    "\1\212\6\0\14\172\2\0\2\172\1\0\1\172\5\0"+
    "\1\146\7\0\2\172\1\0\3\172\2\0\1\173\1\145"+
    "\1\172\6\0\14\173\2\0\2\173\1\0\1\173\5\0"+
    "\1\146\7\0\2\173\1\0\3\173\2\0\1\173\1\0"+
    "\1\173\13\0\1\213\52\0\5\3\1\214\6\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\6\0\14\3\2\0\2\3\1\0\1\3\15\0"+
    "\1\215\1\3\1\0\3\3\4\0\1\3\6\0\10\3"+
    "\1\216\3\3\2\0\2\3\1\0\1\3\15\0\2\3"+
    "\1\0\3\3\4\0\1\3\6\0\2\3\1\217\11\3"+
    "\2\0\2\3\1\0\1\3\15\0\2\3\1\0\3\3"+
    "\4\0\1\3\6\0\2\3\1\220\11\3\2\0\2\3"+
    "\1\0\1\3\15\0\2\3\1\0\3\3\4\0\1\3"+
    "\21\0\1\221\44\0\13\3\1\222\2\0\2\3\1\0"+
    "\1\3\15\0\2\3\1\0\3\3\4\0\1\3\12\0"+
    "\1\223\63\0\1\224\47\0\10\3\1\225\3\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\6\0\10\3\1\226\3\3\2\0\2\3\1\0"+
    "\1\3\15\0\2\3\1\0\3\3\4\0\1\3\6\0"+
    "\5\3\1\227\6\3\2\0\2\3\1\0\1\3\15\0"+
    "\2\3\1\0\3\3\4\0\1\3\6\0\3\3\1\230"+
    "\10\3\2\0\2\3\1\0\1\3\15\0\2\3\1\0"+
    "\3\3\4\0\1\3\6\0\5\3\1\231\6\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\14\0\1\232\51\0\6\3\1\233\5\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\32\0\1\234\53\0\2\235\36\0\14\3\2\0"+
    "\2\3\1\235\1\236\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\6\0\5\3\1\237\6\3\2\0\2\3\1\0"+
    "\1\3\15\0\2\3\1\0\3\3\4\0\1\3\6\0"+
    "\12\3\1\240\1\3\2\0\2\3\1\0\1\3\15\0"+
    "\2\3\1\0\3\3\4\0\1\3\6\0\10\3\1\241"+
    "\3\3\2\0\2\3\1\0\1\3\15\0\2\3\1\0"+
    "\3\3\4\0\1\3\6\0\6\3\1\242\5\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\13\0\1\243\52\0\5\3\1\244\6\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\6\0\12\3\1\245\1\3\2\0\2\3\1\0"+
    "\1\3\15\0\2\3\1\0\3\3\4\0\1\3\6\0"+
    "\14\3\2\0\2\3\1\0\1\3\15\0\2\3\1\0"+
    "\1\3\1\246\1\3\4\0\1\3\6\0\5\3\1\247"+
    "\6\3\2\0\2\3\1\0\1\3\15\0\2\3\1\0"+
    "\3\3\4\0\1\3\6\0\14\3\2\0\2\3\1\0"+
    "\1\3\15\0\2\3\1\0\1\3\1\250\1\3\4\0"+
    "\1\3\6\0\14\3\2\0\2\3\1\0\1\3\15\0"+
    "\2\3\1\251\1\252\2\3\4\0\1\3\6\0\14\3"+
    "\2\0\2\3\1\0\1\3\15\0\2\3\1\253\1\254"+
    "\2\3\4\0\1\3\24\0\1\255\41\0\14\3\2\0"+
    "\1\256\1\3\1\0\1\3\15\0\2\3\1\0\3\3"+
    "\4\0\1\3\24\0\1\257\41\0\14\3\2\0\1\260"+
    "\1\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\14\0\1\261\51\0\6\3\1\262\5\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\14\0\1\263\51\0\6\3\1\264\5\3\2\0"+
    "\2\3\1\0\1\3\15\0\2\3\1\0\3\3\4\0"+
    "\1\3\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6432];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\16\1\13\11\3\1\6\11\13\1\1\0"+
    "\3\1\1\0\1\1\1\0\1\1\2\0\1\11\1\0"+
    "\13\1\1\11\3\1\1\11\1\1\1\0\1\1\3\0"+
    "\2\1\1\0\13\1\1\0\1\1\1\0\1\1\4\0"+
    "\2\1\1\0\12\1\1\11\1\1\1\0\1\1\4\0"+
    "\2\1\1\11\10\1\1\0\1\1\2\0\5\1\1\0"+
    "\1\1\2\0\5\1\1\0\1\1\2\11\5\1\1\11"+
    "\5\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\11\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[180];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
/* Lista con errores sintacticos */

public LinkedList<Errores> ErroresLexicos=new LinkedList<Errores>();
/* Metodo que es llamado al encontrar un error lexico */
private void ErrorScan(int linea, int columna, String valor){
ErroresLexicos.add(new Errores(linea, columna, "Error lexico: caracter "+valor+" no valido") );
}




  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { System.out.println("se encontro errlex: "+yyline+" "+yycolumn+" "+yytext());
		ErrorScan(yyline+1,yycolumn,yytext());
          }
        case 43: break;
        case 2: 
          { System.out.println("Se encontro tid");return new Symbol(simbolos.tid, yyline,yycolumn,yytext());
          }
        case 44: break;
        case 3: 
          { System.out.println("Se encontro tentero");return new Symbol(simbolos.tentero, yyline,yycolumn,yytext());
          }
        case 45: break;
        case 4: 
          { System.out.println("Se encontro tmenos");return new Symbol(simbolos.tmenos, yyline,yycolumn,yytext());
          }
        case 46: break;
        case 5: 
          { System.out.println("Se encontro tmas");return new Symbol(simbolos.tmas, yyline,yycolumn,yytext());
          }
        case 47: break;
        case 6: 
          { System.out.println("Se encontro tmulti");return new Symbol(simbolos.tmulti, yyline,yycolumn,yytext());
          }
        case 48: break;
        case 7: 
          { System.out.println("Se encontro tdiv");return new Symbol(simbolos.tdiv, yyline,yycolumn,yytext());
          }
        case 49: break;
        case 8: 
          { System.out.println("Se encontro tporcent");return new Symbol(simbolos.tporcent, yyline,yycolumn,yytext());
          }
        case 50: break;
        case 9: 
          { System.out.println("Se encontro televa");return new Symbol(simbolos.televa, yyline,yycolumn,yytext());
          }
        case 51: break;
        case 10: 
          { System.out.println("Se encontro tigual");return new Symbol(simbolos.tigual, yyline,yycolumn,yytext());
          }
        case 52: break;
        case 11: 
          { System.out.println("Se encontro tparena");return new Symbol(simbolos.tparena, yyline,yycolumn,yytext());
          }
        case 53: break;
        case 12: 
          { System.out.println("Se encontro tparenc");return new Symbol(simbolos.tparenc, yyline,yycolumn,yytext());
          }
        case 54: break;
        case 13: 
          { System.out.println("Se encontro tmayor");return new Symbol(simbolos.tmayor, yyline,yycolumn,yytext());
          }
        case 55: break;
        case 14: 
          { System.out.println("Se encontro tmenor");return new Symbol(simbolos.tmenor, yyline,yycolumn,yytext());
          }
        case 56: break;
        case 15: 
          { System.out.println("Se encontro tcoma");return new Symbol(simbolos.tcoma, yyline,yycolumn,yytext());
          }
        case 57: break;
        case 16: 
          { System.out.println("Se encontro tdpuntos");return new Symbol(simbolos.tdpuntos, yyline,yycolumn,yytext());
          }
        case 58: break;
        case 17: 
          { 
          }
        case 59: break;
        case 18: 
          { System.out.println("Se encontro tor");return new Symbol(simbolos.tor, yyline,yycolumn,yytext());
          }
        case 60: break;
        case 19: 
          { System.out.println("Se encontro tand");return new Symbol(simbolos.tand, yyline,yycolumn,yytext());
          }
        case 61: break;
        case 20: 
          { System.out.println("Se encontro tdif");return new Symbol(simbolos.tdif, yyline,yycolumn,yytext());
          }
        case 62: break;
        case 21: 
          { System.out.println("Se encontro tdc");return new Symbol(simbolos.tdc, yyline,yycolumn,yytext());
          }
        case 63: break;
        case 22: 
          { System.out.println("Se encontro tdv");return new Symbol(simbolos.tdv, yyline,yycolumn,yytext());
          }
        case 64: break;
        case 23: 
          { System.out.println("Se encontro tcadena");return new Symbol(simbolos.tcadena, yyline,yycolumn,yytext());
          }
        case 65: break;
        case 24: 
          { System.out.println("Se encontro tletra");return new Symbol(simbolos.tletra, yyline,yycolumn,yytext());
          }
        case 66: break;
        case 25: 
          { System.out.println("Se encontro tvar");return new Symbol(simbolos.tvar, yyline,yycolumn,yytext());
          }
        case 67: break;
        case 26: 
          { System.out.println("Se encontro tfin");return new Symbol(simbolos.tfin, yyline,yycolumn,yytext());
          }
        case 68: break;
        case 27: 
          { System.out.println("Se encontro ttbool");return new Symbol(simbolos.ttbool, yyline,yycolumn,yytext());
          }
        case 69: break;
        case 28: 
          { System.out.println("Se encontro tpara");return new Symbol(simbolos.tpara, yyline,yycolumn,yytext());
          }
        case 70: break;
        case 29: 
          { System.out.println("Se encontro ttletra");return new Symbol(simbolos.ttletra, yyline,yycolumn,yytext());
          }
        case 71: break;
        case 30: 
          { System.out.println("Se encontro tfalso");return new Symbol(simbolos.tfalso, yyline,yycolumn,yytext());
          }
        case 72: break;
        case 31: 
          { System.out.println("Se encontro thacer");return new Symbol(simbolos.thacer, yyline,yycolumn,yytext());
          }
        case 73: break;
        case 32: 
          { System.out.println("Se encontro thasta");return new Symbol(simbolos.thasta, yyline,yycolumn,yytext());
          }
        case 74: break;
        case 33: 
          { System.out.println("Se encontro ttentero");return new Symbol(simbolos.ttentero, yyline,yycolumn,yytext());
          }
        case 75: break;
        case 34: 
          { System.out.println("Se encontro taletra");return new Symbol(simbolos.taletra, yyline,yycolumn,yytext());
          }
        case 76: break;
        case 35: 
          { System.out.println("Se encontro ttcadena");return new Symbol(simbolos.ttcadena, yyline,yycolumn,yytext());
          }
        case 77: break;
        case 36: 
          { System.out.println("Se encontro tpath");return new Symbol(simbolos.tpath, yyline,yycolumn,yytext());
          }
        case 78: break;
        case 37: 
          { System.out.println("Se encontro tmientras");return new Symbol(simbolos.tmientras, yyline,yycolumn,yytext());
          }
        case 79: break;
        case 38: 
          { System.out.println("Se encontro tverdadero");return new Symbol(simbolos.tverdadero, yyline,yycolumn,yytext());
          }
        case 80: break;
        case 39: 
          { System.out.println("Se encontro tsepara");return new Symbol(simbolos.tsepara, yyline,yycolumn,yytext());
          }
        case 81: break;
        case 40: 
          { System.out.println("Se encontro tconcat");return new Symbol(simbolos.tconcat, yyline,yycolumn,yytext());
          }
        case 82: break;
        case 41: 
          { System.out.println("Se encontro tcrear");return new Symbol(simbolos.tcrear, yyline,yycolumn,yytext());
          }
        case 83: break;
        case 42: 
          { System.out.println("Se encontro tanexar");return new Symbol(simbolos.tanexar, yyline,yycolumn,yytext());
          }
        case 84: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(simbolos.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
