
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 11 19:02:14 CST 2014
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class simbolos {
  /* terminals */
  public static final int tcrear = 31;
  public static final int thasta = 37;
  public static final int tpath = 33;
  public static final int tigual = 15;
  public static final int tvar = 20;
  public static final int tletra = 7;
  public static final int ttbool = 4;
  public static final int tmas = 11;
  public static final int tor = 40;
  public static final int tid = 21;
  public static final int tporcent = 38;
  public static final int tcadena = 10;
  public static final int tmenos = 12;
  public static final int televa = 39;
  public static final int tmenor = 19;
  public static final int ttcadena = 5;
  public static final int tfin = 25;
  public static final int ttletra = 3;
  public static final int tdpuntos = 32;
  public static final int tmayor = 18;
  public static final int tand = 41;
  public static final int tcoma = 29;
  public static final int EOF = 0;
  public static final int tsepara = 30;
  public static final int tdiv = 14;
  public static final int error = 1;
  public static final int tfalso = 9;
  public static final int tmulti = 13;
  public static final int thacer = 24;
  public static final int tverdadero = 8;
  public static final int taletra = 27;
  public static final int tdv = 36;
  public static final int tdif = 42;
  public static final int tparenc = 17;
  public static final int tparena = 16;
  public static final int tpara = 26;
  public static final int tmientras = 23;
  public static final int tcorc = 22;
  public static final int tconcat = 28;
  public static final int tentero = 6;
  public static final int tdc = 35;
  public static final int ttentero = 2;
  public static final int tanexar = 34;
}

